swagger: '2.0'
info:
    title: Workshop people api
    description: This is the description of the people api to practices the microservices configuration in GCP
    version: 1.0.0
host: $hostESP
security:
    - api_key: []
    - firebase: []
schemes:
    - https
produces:
    - application/json
paths:
    /people:
        get:
            summary: Get paginated list of people
            operationId: people
            x-google-backend:
                address: https://europe-west1-invertible-env-265310.cloudfunctions.net/read_people
            responses:
                200:
                    description: Success response from services
                    schema:
                        type: object
                        properties:
                            metadata:
                                type: object
                                properties:
                                    limit:
                                        type: number
                                        description: Size of the page
                                    offset:
                                        type: number
                                        description: Index of the page
                                    total:
                                        type: number
                                        description: Total number of items in the data base
                            data:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        name:
                                            type: string
                                            description: Name of the person
                                        surname:
                                            type: string
                                            description: Surname of the person
                                        email:
                                            type: string
                                            description: email of the person
                500:
                    description: Service controled error
                    schema:
                        type: string
        post:
            summary: Create a nuew people
            operationId: create_people
            x-google-backend:
                address: https://europe-west1-invertible-env-265310.cloudfunctions.net/create_person
            responses:
                201:
                    description: Person created successfully
                    schema:
                        type: object
                        properties:
                            message:
                                type: string
                                description: Success message
                400:
                    description: Wrong body in the request
                    schema:
                        type: string
                500:
                    description: Service controled error
                    schema:
                        type: string
    /people/{code}:
        get:
            summary: Read information about one person
            parameters:
                - in: path
                  name: code
                  type: integer
                  required: true
            operationId: read_one_person
            x-google-backend:
                address: https://europe-west1-invertible-env-265310.cloudfunctions.net/read_one_person
            responses:
                200:
                    description: Information about one person
                    schema:
                        type: object
                        properties:
                            name:
                                type: string
                            surname:
                                type: string
                            email:
                                type: string
                400:
                    description: Wrong id
                    schema:
                        type: string
                404:
                    description: Person not found
                    schema:
                        type: string
                500:
                    description: Service controled error
                    schema:
                        type: string

                                
securityDefinitions:
    api_key:
        type: "apiKey"
        name: "key"
        in: "query"
    firebase:
        authorizationUrl: ""
        flow: "implicit"
        type: "oauth2"
        x-google-issuer: "https://securetoken.google.com/invertible-env-265310"
        x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
        x-google-audiences: "invertible-env-265310"
